import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const QUIZZES = [
  {
    skill: "Python",
    title: "Python — Fondamentaux & Best Practices",
    description: "Variables, structures de données, OOP, décorateurs, async.",
    difficulty: "INTERMEDIATE",
    timeLimit: 12,
    questions: JSON.stringify([
      {
        id: "py1",
        text: "Quel est le résultat de `list(map(lambda x: x**2, [1,2,3]))`?",
        options: ["[1, 4, 9]", "[2, 4, 6]", "[1, 2, 3]", "Erreur TypeError"],
        correctIndex: 0,
        explanation: "map applique la fonction lambda à chaque élément, produisant les carrés.",
      },
      {
        id: "py2",
        text: "Qu'est-ce qu'un décorateur en Python ?",
        options: [
          "Une classe qui hérite d'une autre",
          "Une fonction qui prend une fonction en argument et retourne une nouvelle fonction",
          "Un commentaire de documentation",
          "Un type d'annotation de variable",
        ],
        correctIndex: 1,
        explanation: "Un décorateur est un pattern de higher-order function qui enveloppe une fonction existante.",
      },
      {
        id: "py3",
        text: "Quelle est la différence entre `deepcopy` et `copy` ?",
        options: [
          "Il n'y a pas de différence",
          "`copy` copie l'objet et ses références, `deepcopy` copie récursivement tous les objets imbriqués",
          "`deepcopy` est plus rapide",
          "`copy` ne fonctionne pas avec les listes",
        ],
        correctIndex: 1,
        explanation: "copy.copy() crée une copie superficielle (shallow), copy.deepcopy() crée une copie profonde (deep) de tous les objets imbriqués.",
      },
      {
        id: "py4",
        text: "Que retourne `type([])` ?",
        options: ["array", "<class 'list'>", "list", "None"],
        correctIndex: 1,
        explanation: "type() retourne le type de l'objet sous forme de classe.",
      },
      {
        id: "py5",
        text: "Comment déclarer une méthode de classe (pas d'instance) en Python ?",
        options: [
          "@staticmethod + self comme premier param",
          "@classmethod + cls comme premier param",
          "Aucun décorateur, juste ne pas utiliser self",
          "@property",
        ],
        correctIndex: 1,
        explanation: "@classmethod reçoit la classe (cls) comme premier argument au lieu de l'instance (self).",
      },
      {
        id: "py6",
        text: "Quelle instruction permet d'itérer sur les clés ET valeurs d'un dict ?",
        options: [
          "for k in d.keys()",
          "for k, v in d.items()",
          "for k, v in d.values()",
          "for k, v in enumerate(d)",
        ],
        correctIndex: 1,
        explanation: "dict.items() retourne des tuples (clé, valeur) permettant de les déstructurer directement.",
      },
      {
        id: "py7",
        text: "Que fait le mot-clé `yield` ?",
        options: [
          "Retourne une valeur et termine la fonction",
          "Suspend la fonction et retourne une valeur, permettant de reprendre à ce point",
          "Lève une exception",
          "Attend la fin d'une coroutine async",
        ],
        correctIndex: 1,
        explanation: "yield transforme une fonction en générateur — elle peut produire plusieurs valeurs successives sans tout charger en mémoire.",
      },
      {
        id: "py8",
        text: "Quelle est la complexité temporelle de `in` sur un set Python ?",
        options: ["O(n)", "O(log n)", "O(1) en moyenne", "O(n²)"],
        correctIndex: 2,
        explanation: "Les sets utilisent une table de hachage — la recherche est O(1) en moyenne.",
      },
      {
        id: "py9",
        text: "Que signifie `*args` dans une définition de fonction ?",
        options: [
          "Un argument obligatoire nommé args",
          "Tous les arguments keyword",
          "Un nombre variable d'arguments positionnels passés comme tuple",
          "Un pointeur vers une fonction",
        ],
        correctIndex: 2,
        explanation: "*args capture les arguments positionnels supplémentaires dans un tuple.",
      },
      {
        id: "py10",
        text: "Comment lire un fichier ligne par ligne de manière efficace en mémoire ?",
        options: [
          "f.read().split('\\n')",
          "f.readlines()",
          "Itérer directement sur l'objet fichier avec `for line in f`",
          "f.readline() dans une boucle while True",
        ],
        correctIndex: 2,
        explanation: "Itérer sur l'objet fichier est memory-efficient car Python lit une ligne à la fois sans tout charger.",
      },
    ]),
  },
  {
    skill: "JavaScript",
    title: "JavaScript — ES6+ & Async",
    description: "Closures, promises, event loop, modules, types.",
    difficulty: "INTERMEDIATE",
    timeLimit: 12,
    questions: JSON.stringify([
      {
        id: "js1",
        text: "Quelle est la différence entre `var`, `let` et `const` ?",
        options: [
          "Aucune différence en pratique",
          "`var` est function-scoped et hoisted, `let`/`const` sont block-scoped",
          "`const` ne peut pas stocker des objets",
          "`let` est global, `const` est local",
        ],
        correctIndex: 1,
        explanation: "var a une portée fonction et est hoistée. let et const ont une portée bloc. const interdit la réaffectation mais pas la mutation d'objets.",
      },
      {
        id: "js2",
        text: "Qu'est-ce qu'une closure ?",
        options: [
          "Une fonction sans return",
          "Une fonction qui ferme son scope et n'a plus accès aux variables extérieures",
          "Une fonction interne qui capture et mémorise les variables de son scope englobant",
          "Une classe ES6",
        ],
        correctIndex: 2,
        explanation: "Une closure est une fonction qui 'se souvient' de l'environnement dans lequel elle a été créée, y compris ses variables libres.",
      },
      {
        id: "js3",
        text: "Que vaut `typeof null` ?",
        options: ["'null'", "'undefined'", "'object'", "'boolean'"],
        correctIndex: 2,
        explanation: "C'est un bug historique de JavaScript — typeof null retourne 'object' depuis la première version.",
      },
      {
        id: "js4",
        text: "Comment fonctionne l'event loop JavaScript ?",
        options: [
          "JavaScript est multi-threadé et utilise plusieurs boucles",
          "Le call stack exécute le code synchrone, les callbacks async sont mis en queue et exécutés quand le stack est vide",
          "Les Promises bloquent le thread principal",
          "setTimeout garantit une exécution exacte après le délai indiqué",
        ],
        correctIndex: 1,
        explanation: "L'event loop surveille le call stack et la callback queue — quand le stack est vide, elle pousse le prochain callback de la queue.",
      },
      {
        id: "js5",
        text: "Que retourne `Promise.all([p1, p2, p3])` ?",
        options: [
          "La première promise résolue",
          "Une promise résolue avec un tableau des résultats si toutes réussissent, rejetée dès qu'une échoue",
          "Une promise qui attend la plus lente",
          "Un tableau de promises non résolues",
        ],
        correctIndex: 1,
        explanation: "Promise.all résout quand toutes les promises réussissent, ou rejette immédiatement dès qu'une seule échoue.",
      },
      {
        id: "js6",
        text: "Quelle est la sortie de `[1,2,3].map(String)` ?",
        options: ["['1','2','3']", "[1,2,3]", "['String','String','String']", "Erreur"],
        correctIndex: 0,
        explanation: "String est passé comme callback — il est appelé avec (value, index, array) mais String() sur un nombre retourne sa représentation string.",
      },
      {
        id: "js7",
        text: "Comment fonctionne le destructuring d'objet avec valeur par défaut ?",
        options: [
          "const { a = 5 } = obj — a vaut 5 si obj.a est undefined",
          "const { a: 5 } = obj",
          "const { a ?? 5 } = obj",
          "Ce n'est pas possible en JS natif",
        ],
        correctIndex: 0,
        explanation: "La syntaxe { a = defaultValue } assigne la valeur par défaut si la propriété est undefined ou absente.",
      },
      {
        id: "js8",
        text: "Qu'est-ce que le prototype chain en JavaScript ?",
        options: [
          "Un design pattern de chaining de méthodes",
          "Le mécanisme par lequel un objet hérite des propriétés de son prototype via __proto__",
          "Une façon d'importer des modules",
          "La chaîne d'appels de callbacks",
        ],
        correctIndex: 1,
        explanation: "Chaque objet a une propriété __proto__ pointant vers son prototype. JS remonte cette chaîne pour résoudre les propriétés.",
      },
      {
        id: "js9",
        text: "Que fait `Object.freeze()` ?",
        options: [
          "Supprime toutes les propriétés de l'objet",
          "Rend l'objet immutable — aucune propriété ne peut être ajoutée, modifiée ou supprimée",
          "Convertit l'objet en JSON",
          "Crée une copie profonde de l'objet",
        ],
        correctIndex: 1,
        explanation: "Object.freeze() empêche toute modification de l'objet. Attention : c'est un freeze superficiel — les objets imbriqués restent mutables.",
      },
      {
        id: "js10",
        text: "Quelle méthode de tableau retourne un nouveau tableau sans modifier l'original ?",
        options: [
          "splice()",
          "sort()",
          "push()",
          "map()",
        ],
        correctIndex: 3,
        explanation: "map(), filter(), slice(), concat() retournent de nouveaux tableaux. splice(), sort(), push(), pop() modifient le tableau en place.",
      },
    ]),
  },
  {
    skill: "React",
    title: "React — Hooks, State & Performance",
    description: "Composants, hooks, rendu, context, optimisation.",
    difficulty: "INTERMEDIATE",
    timeLimit: 12,
    questions: JSON.stringify([
      {
        id: "rct1",
        text: "Quelle est la règle principale des hooks React ?",
        options: [
          "Ils ne peuvent être utilisés que dans des classes",
          "Ils doivent être appelés au top-level d'un composant fonctionnel, pas dans des conditions ou boucles",
          "Chaque composant ne peut avoir qu'un seul hook",
          "Ils ne peuvent pas être utilisés dans des composants enfants",
        ],
        correctIndex: 1,
        explanation: "Les hooks doivent toujours être appelés dans le même ordre à chaque rendu — donc pas dans des conditions, boucles ou fonctions imbriquées.",
      },
      {
        id: "rct2",
        text: "Quand `useEffect` s'exécute-t-il avec un tableau de dépendances vide `[]` ?",
        options: [
          "À chaque rendu",
          "Uniquement au premier rendu (mount)",
          "Jamais",
          "Uniquement au démontage (unmount)",
        ],
        correctIndex: 1,
        explanation: "useEffect avec [] simule componentDidMount — il s'exécute une seule fois après le premier rendu.",
      },
      {
        id: "rct3",
        text: "Quelle est la différence entre `useMemo` et `useCallback` ?",
        options: [
          "Ils sont identiques",
          "useMemo mémoïse une valeur calculée, useCallback mémoïse une fonction",
          "useCallback mémoïse une valeur, useMemo mémoïse une fonction",
          "useMemo est pour les classes, useCallback pour les fonctions",
        ],
        correctIndex: 1,
        explanation: "useMemo(() => computeValue(), deps) mémoïse le résultat d'un calcul. useCallback(() => fn, deps) mémoïse la référence de la fonction.",
      },
      {
        id: "rct4",
        text: "Pourquoi la clé (`key`) est-elle importante dans les listes React ?",
        options: [
          "Elle améliore le CSS",
          "Elle n'est pas importante, c'est juste une convention",
          "Elle aide React à identifier quels éléments ont changé pour optimiser le re-rendu",
          "Elle doit toujours être l'index du tableau",
        ],
        correctIndex: 2,
        explanation: "React utilise les clés pour associer les éléments DOM virtuels entre les renders et minimiser les mutations DOM réelles.",
      },
      {
        id: "rct5",
        text: "Qu'est-ce que le Context API résout ?",
        options: [
          "La gestion des requêtes HTTP",
          "Le prop drilling — passer des données à travers plusieurs niveaux de composants sans passer par les props",
          "L'optimisation du rendu",
          "La gestion des effets de bord",
        ],
        correctIndex: 1,
        explanation: "Context permet de partager des données globales (auth, thème) sans les passer manuellement à chaque composant intermédiaire.",
      },
      {
        id: "rct6",
        text: "Comment éviter les re-rendus inutiles d'un composant enfant ?",
        options: [
          "Utiliser useState dans l'enfant",
          "Envelopper le composant avec React.memo() et mémoïser les callbacks passés en props",
          "Utiliser useEffect",
          "Utiliser useRef",
        ],
        correctIndex: 1,
        explanation: "React.memo compare les props superficiellement. Si les callbacks sont recréés à chaque rendu parent, il faut aussi useCallback pour stabiliser leurs références.",
      },
      {
        id: "rct7",
        text: "Que fait `useRef` principalement ?",
        options: [
          "Il crée un état qui déclenche un re-rendu quand il change",
          "Il persiste une valeur mutable entre les rendus sans déclencher de re-rendu",
          "Il référence le composant parent",
          "Il remplace useState pour les valeurs primitives",
        ],
        correctIndex: 1,
        explanation: "useRef retourne un objet {current} dont la mutation ne déclenche pas de re-rendu — utile pour accéder au DOM ou stocker des valeurs persistantes.",
      },
      {
        id: "rct8",
        text: "Quelle est la forme correcte pour mettre à jour un objet dans useState ?",
        options: [
          "setState(state.key = newValue)",
          "setState({ ...state, key: newValue })",
          "state.key = newValue; setState(state)",
          "setState(Object.assign(state, { key: newValue }))",
        ],
        correctIndex: 1,
        explanation: "React requiert une nouvelle référence d'objet pour détecter le changement. Il faut spreader l'état précédent et remplacer les clés modifiées.",
      },
      {
        id: "rct9",
        text: "Qu'est-ce que le Reconciliation en React ?",
        options: [
          "Le processus de résolution des conflits entre composants",
          "L'algorithme qui compare le virtual DOM précédent et le nouveau pour minimiser les mises à jour réelles du DOM",
          "La synchronisation des states entre composants",
          "Le processus de compilation JSX",
        ],
        correctIndex: 1,
        explanation: "React Fiber (l'algorithme de réconciliation) compare deux arbres de virtual DOM et calcule le diff minimum à appliquer au vrai DOM.",
      },
      {
        id: "rct10",
        text: "Quand doit-on utiliser `useReducer` plutôt que `useState` ?",
        options: [
          "Jamais, useState suffit toujours",
          "Quand la logique de mise à jour est complexe avec plusieurs sous-valeurs interdépendantes ou beaucoup de transitions d'état",
          "Uniquement pour les tableaux",
          "Quand on veut éviter les re-rendus",
        ],
        correctIndex: 1,
        explanation: "useReducer est préférable pour des états complexes avec plusieurs actions (pattern similaire à Redux) ou quand l'état suivant dépend du précédent.",
      },
    ]),
  },
  {
    skill: "SQL",
    title: "SQL — Requêtes & Optimisation",
    description: "Jointures, agrégations, indexes, transactions, fenêtres.",
    difficulty: "INTERMEDIATE",
    timeLimit: 12,
    questions: JSON.stringify([
      {
        id: "sql1",
        text: "Quelle est la différence entre `INNER JOIN` et `LEFT JOIN` ?",
        options: [
          "Aucune différence",
          "INNER JOIN retourne uniquement les lignes avec correspondance dans les deux tables. LEFT JOIN retourne toutes les lignes de la table gauche, avec NULL si pas de correspondance à droite",
          "LEFT JOIN est plus rapide",
          "INNER JOIN inclut les doublons, LEFT JOIN non",
        ],
        correctIndex: 1,
        explanation: "INNER JOIN = intersection. LEFT JOIN = toutes les lignes gauche + correspondances droite (NULL si absent).",
      },
      {
        id: "sql2",
        text: "À quoi sert la clause `HAVING` ?",
        options: [
          "Filtrer les lignes avant le GROUP BY",
          "Filtrer les groupes après agrégation, là où WHERE ne peut pas être utilisé",
          "Trier les résultats",
          "Limiter le nombre de résultats",
        ],
        correctIndex: 1,
        explanation: "WHERE filtre avant GROUP BY (sur des lignes). HAVING filtre après GROUP BY (sur des groupes), permettant d'utiliser des fonctions d'agrégation.",
      },
      {
        id: "sql3",
        text: "Qu'est-ce qu'un index et quand l'utiliser ?",
        options: [
          "Un alias de table",
          "Une structure de données accélérant les lookups sur une colonne, utile sur les colonnes fréquemment filtrées/jointures",
          "Une vue matérialisée",
          "Un type de contrainte d'unicité uniquement",
        ],
        correctIndex: 1,
        explanation: "Un index (B-tree par défaut) accélère SELECT mais ralentit INSERT/UPDATE. Créer sur les colonnes de WHERE, JOIN ON, ORDER BY fréquents.",
      },
      {
        id: "sql4",
        text: "Que fait `ROW_NUMBER() OVER (PARTITION BY dept ORDER BY salary DESC)` ?",
        options: [
          "Trie les résultats par salaire",
          "Attribue un rang unique à chaque ligne dans chaque groupe (dept), ordonné par salaire décroissant",
          "Compte le nombre d'employés par département",
          "Calcule le salaire moyen par département",
        ],
        correctIndex: 1,
        explanation: "C'est une fonction de fenêtre (window function). PARTITION BY divise en groupes, ORDER BY détermine le rang — idéal pour 'top N par groupe'.",
      },
      {
        id: "sql5",
        text: "Quelle est la différence entre `DELETE`, `TRUNCATE` et `DROP` ?",
        options: [
          "Ce sont des synonymes",
          "DELETE supprime des lignes filtrables et est rollbackable. TRUNCATE vide la table entière rapidement. DROP supprime la table et sa structure",
          "TRUNCATE est plus lent que DELETE",
          "DROP garde la structure de la table",
        ],
        correctIndex: 1,
        explanation: "DELETE : ligne par ligne, WHERE possible, transactionnel. TRUNCATE : reset rapide, pas de WHERE, difficile à rollback. DROP : supprime table + données + structure.",
      },
      {
        id: "sql6",
        text: "Qu'est-ce qu'une CTE (Common Table Expression) ?",
        options: [
          "Un type d'index",
          "Un résultat intermédiaire nommé défini avec WITH, réutilisable dans la requête principale",
          "Une contrainte de table",
          "Un type de jointure",
        ],
        correctIndex: 1,
        explanation: "WITH cte AS (SELECT ...) SELECT * FROM cte — les CTEs rendent les requêtes complexes plus lisibles et permettent la récursivité.",
      },
      {
        id: "sql7",
        text: "Que signifie ACID pour les transactions ?",
        options: [
          "Async, Concurrent, Indexed, Distributed",
          "Atomicité, Cohérence, Isolation, Durabilité",
          "Available, Consistent, Independent, Durable",
          "Automated, Cached, Incremental, Dynamic",
        ],
        correctIndex: 1,
        explanation: "ACID garantit l'intégrité des transactions : tout ou rien (A), état valide (C), transactions isolées (I), données persistées après commit (D).",
      },
      {
        id: "sql8",
        text: "Comment optimiser une requête avec `EXPLAIN ANALYZE` ?",
        options: [
          "En ajoutant ORDER BY",
          "En analysant le plan d'exécution pour identifier les Seq Scan coûteux et ajouter des index appropriés",
          "En utilisant SELECT *",
          "En supprimant les jointures",
        ],
        correctIndex: 1,
        explanation: "EXPLAIN ANALYZE exécute la requête et affiche le plan réel : coûts, temps, type de scan. Un Seq Scan sur une grande table indique souvent un index manquant.",
      },
      {
        id: "sql9",
        text: "Quelle est la différence entre `UNION` et `UNION ALL` ?",
        options: [
          "UNION ALL est interdit en SQL standard",
          "UNION déduplique les lignes (plus lent), UNION ALL conserve tous les doublons (plus rapide)",
          "UNION est plus rapide que UNION ALL",
          "Ils sont identiques",
        ],
        correctIndex: 1,
        explanation: "UNION effectue un DISTINCT implicite (coût supplémentaire). UNION ALL empile simplement les résultats sans déduplication — préférer UNION ALL quand les doublons sont acceptables.",
      },
      {
        id: "sql10",
        text: "Qu'est-ce qu'un deadlock en base de données ?",
        options: [
          "Une requête qui tourne indéfiniment",
          "Une situation où deux transactions s'attendent mutuellement sur des verrous qu'elles détiennent",
          "Un index corrompu",
          "Une contrainte violée",
        ],
        correctIndex: 1,
        explanation: "T1 verrouille A et attend B. T2 verrouille B et attend A. Cycle d'attente infini — le SGBD détecte et annule une des deux transactions.",
      },
    ]),
  },
  {
    skill: "DevOps",
    title: "DevOps — Docker, K8s & CI/CD",
    description: "Conteneurs, orchestration, pipelines, infrastructure as code.",
    difficulty: "INTERMEDIATE",
    timeLimit: 12,
    questions: JSON.stringify([
      {
        id: "dv1",
        text: "Quelle est la différence entre une image Docker et un conteneur ?",
        options: [
          "Ce sont des synonymes",
          "Une image est un template immuable. Un conteneur est une instance en cours d'exécution de cette image",
          "Un conteneur est plus léger qu'une image",
          "Une image s'exécute sur le réseau, un conteneur en local",
        ],
        correctIndex: 1,
        explanation: "Image = blueprint read-only (Dockerfile compilé). Conteneur = instance live avec une layer d'écriture propre, créée depuis l'image.",
      },
      {
        id: "dv2",
        text: "Que fait `COPY` vs `ADD` dans un Dockerfile ?",
        options: [
          "Ils sont identiques",
          "COPY copie des fichiers locaux. ADD fait la même chose mais supporte aussi les URLs et l'extraction automatique de tar",
          "ADD est deprecated",
          "COPY supporte les URLs, ADD non",
        ],
        correctIndex: 1,
        explanation: "Préférer COPY pour la transparence — son comportement est prévisible. ADD est utile uniquement pour extraire des archives locales.",
      },
      {
        id: "dv3",
        text: "Qu'est-ce qu'un Kubernetes Pod ?",
        options: [
          "Un nœud dans le cluster",
          "La plus petite unité déployable K8s — un ou plusieurs conteneurs partageant le réseau et le stockage",
          "Un namespace K8s",
          "Un load balancer",
        ],
        correctIndex: 1,
        explanation: "Un Pod encapsule un ou plusieurs conteneurs co-localisés qui partagent l'IP, les ports et les volumes. C'est l'unité d'orchestration de base.",
      },
      {
        id: "dv4",
        text: "Quelle est la différence entre `Deployment` et `StatefulSet` en K8s ?",
        options: [
          "Ils sont identiques",
          "Deployment pour les workloads stateless (pods interchangeables). StatefulSet pour les workloads avec état persistant (DB, queues) — identité stable et ordre de démarrage",
          "StatefulSet est plus récent et remplace Deployment",
          "Deployment ne supporte pas le scaling",
        ],
        correctIndex: 1,
        explanation: "StatefulSet garantit un nom stable (pod-0, pod-1), un stockage persistant par pod et un ordre d'opération — essentiel pour MySQL, Kafka, etc.",
      },
      {
        id: "dv5",
        text: "Que teste une health check `liveness probe` vs `readiness probe` ?",
        options: [
          "Ce sont les mêmes",
          "Liveness : le conteneur est-il vivant (sinon restart). Readiness : le conteneur est-il prêt à recevoir du trafic (sinon retiré du load balancer)",
          "Readiness vérifie les dépendances externes, liveness vérifie le code",
          "Liveness est pour la prod, readiness pour le staging",
        ],
        correctIndex: 1,
        explanation: "Liveness échoue → K8s redémarre le conteneur. Readiness échoue → K8s retire le pod du Service endpoint mais ne le redémarre pas.",
      },
      {
        id: "dv6",
        text: "Qu'est-ce que l'infrastructure as code (IaC) ?",
        options: [
          "Écrire des scripts bash pour déployer",
          "Définir et provisionner l'infrastructure via des fichiers de configuration versionnés (Terraform, Pulumi, CloudFormation)",
          "Documenter l'infrastructure dans un wiki",
          "Utiliser une interface graphique cloud",
        ],
        correctIndex: 1,
        explanation: "IaC permet de versionner, tester et reproduire l'infrastructure. Le state est géré par l'outil (terraform.tfstate), les changements sont planifiés avant application.",
      },
      {
        id: "dv7",
        text: "Dans un pipeline CI/CD, que signifie 'shift left' ?",
        options: [
          "Déplacer les tests en production",
          "Détecter les problèmes le plus tôt possible dans le cycle de développement (lint, tests unitaires avant les tests d'intégration)",
          "Déployer de droite à gauche",
          "Réduire le nombre de branches Git",
        ],
        correctIndex: 1,
        explanation: "Shift left = déplacer les contrôles qualité vers la gauche du pipeline (tôt). Plus un bug est détecté tôt, moins il coûte cher à corriger.",
      },
      {
        id: "dv8",
        text: "Quelle est la différence entre déploiement Blue/Green et Canary ?",
        options: [
          "Ce sont des termes identiques",
          "Blue/Green bascule 100% du trafic vers la nouvelle version. Canary envoie progressivement un % croissant du trafic vers la nouvelle version",
          "Canary est plus risqué que Blue/Green",
          "Blue/Green ne permet pas de rollback",
        ],
        correctIndex: 1,
        explanation: "Blue/Green = deux environnements, bascule instantanée. Canary = rollout graduel permettant de tester sur un sous-ensemble d'utilisateurs réels.",
      },
      {
        id: "dv9",
        text: "À quoi sert un ConfigMap dans Kubernetes ?",
        options: [
          "Stocker des secrets de manière sécurisée",
          "Stocker des données de configuration non-sensibles (env vars, fichiers de config) découplées des images conteneur",
          "Configurer le réseau du cluster",
          "Définir les ressources CPU/RAM des pods",
        ],
        correctIndex: 1,
        explanation: "ConfigMap découple la config de l'image. Pour les données sensibles (passwords, tokens), utiliser Secret (même principe mais encodé et avec RBAC).",
      },
      {
        id: "dv10",
        text: "Qu'est-ce que le 'GitOps' ?",
        options: [
          "Utiliser Git pour le versioning du code uniquement",
          "Utiliser Git comme source de vérité pour l'infrastructure et les déploiements — tout changement passe par une PR, un opérateur (ArgoCD, Flux) synchronise l'état réel",
          "Une alternative à GitHub",
          "Un workflow Git avec des branches obligatoires",
        ],
        correctIndex: 1,
        explanation: "En GitOps, le repo Git est la source de vérité. ArgoCD ou Flux observent le repo et reconcilent l'état K8s avec ce qui est déclaré dans Git.",
      },
    ]),
  },
  {
    skill: "Data Science",
    title: "Data Science — ML & Statistiques",
    description: "Modèles, évaluation, features, biais, statistiques.",
    difficulty: "INTERMEDIATE",
    timeLimit: 12,
    questions: JSON.stringify([
      {
        id: "ds1",
        text: "Qu'est-ce que l'overfitting et comment le détecter ?",
        options: [
          "Le modèle est trop simple et a une erreur élevée sur les données d'entraînement",
          "Le modèle performe très bien en training mais mal en validation/test — gap important entre les deux scores",
          "Le modèle prend trop de temps à s'entraîner",
          "Le dataset est trop grand",
        ],
        correctIndex: 1,
        explanation: "L'overfitting = le modèle mémorise le training set au lieu d'apprendre des patterns généralisables. Un gap train/val élevé est le signe principal.",
      },
      {
        id: "ds2",
        text: "Quelle métrique utiliser pour un problème de classification déséquilibré (99% classe A, 1% classe B) ?",
        options: [
          "Accuracy",
          "F1-score ou AUC-ROC, car l'accuracy est trompeuse (un modèle qui prédit toujours A aurait 99%)",
          "MSE",
          "R²",
        ],
        correctIndex: 1,
        explanation: "Sur des datasets déséquilibrés, l'accuracy est inutile. F1-score balance précision/rappel. AUC-ROC mesure la capacité discriminante indépendamment du seuil.",
      },
      {
        id: "ds3",
        text: "Qu'est-ce que la validation croisée (cross-validation) ?",
        options: [
          "Tester le modèle sur un seul jeu de test",
          "Diviser les données en K folds, entraîner K fois sur K-1 folds et évaluer sur le fold restant, puis moyenner les scores",
          "Entraîner plusieurs modèles différents",
          "Dupliquer les données pour augmenter le dataset",
        ],
        correctIndex: 1,
        explanation: "K-fold CV donne une estimation plus robuste de la performance généralisation en utilisant toutes les données à la fois pour le train et le test.",
      },
      {
        id: "ds4",
        text: "Quelle est la différence entre régression L1 (Lasso) et L2 (Ridge) ?",
        options: [
          "Aucune différence pratique",
          "L1 (Lasso) produit des solutions sparses (certains coefficients à 0, sélection de features). L2 (Ridge) réduit tous les coefficients sans les annuler",
          "L2 est utilisé pour la classification, L1 pour la régression",
          "L1 est plus rapide à calculer",
        ],
        correctIndex: 1,
        explanation: "Lasso (L1) pénalise la somme des valeurs absolues → sparsité. Ridge (L2) pénalise la somme des carrés → shrinkage uniforme. Elastic Net combine les deux.",
      },
      {
        id: "ds5",
        text: "Qu'est-ce que le biais (bias) vs la variance dans le trade-off ?",
        options: [
          "Biais = erreur aléatoire, Variance = erreur systématique",
          "Biais = erreur systématique due à des hypothèses de modèle trop simplistes. Variance = sensibilité aux fluctuations du training set",
          "Ce sont des synonymes",
          "Biais mesure l'équité du modèle, variance mesure la rapidité",
        ],
        correctIndex: 1,
        explanation: "High bias = underfitting (modèle trop simple). High variance = overfitting (trop sensible aux données d'entraînement). L'objectif est de trouver le bon équilibre.",
      },
      {
        id: "ds6",
        text: "Pourquoi normaliser/standardiser les features ?",
        options: [
          "Pour accélérer le chargement des données",
          "Pour que les features à grande échelle ne dominent pas l'optimisation — essentiel pour les algorithmes basés sur les distances (KNN, SVM, gradient descent)",
          "Pour rendre les données plus lisibles",
          "Ce n'est jamais nécessaire",
        ],
        correctIndex: 1,
        explanation: "Sans normalisation, une feature en milliers (revenus) domine une feature en 0-1 (score). Les arbres de décision sont insensibles à l'échelle, pas les modèles linéaires.",
      },
      {
        id: "ds7",
        text: "Qu'est-ce que le data leakage ?",
        options: [
          "Des données qui fuient hors du serveur",
          "L'introduction involontaire d'informations du future ou du test set dans le training — produit des métriques artificiellement bonnes non reproductibles en prod",
          "Des valeurs manquantes dans le dataset",
          "Un dataset trop grand pour la mémoire",
        ],
        correctIndex: 1,
        explanation: "Ex : normaliser avant de splitter (les stats du test contaminent le train), inclure une feature calculée après la target. Le leakage cause des modèles qui semblent parfaits mais échouent en prod.",
      },
      {
        id: "ds8",
        text: "Quelle est la complexité de l'algorithme KNN pour la prédiction ?",
        options: [
          "O(1)",
          "O(log n)",
          "O(n × d) où n est la taille du dataset et d le nombre de dimensions",
          "O(n²)",
        ],
        correctIndex: 2,
        explanation: "KNN calcule la distance entre le point à prédire et tous les points d'entraînement — O(n×d). Optimisations possibles avec des KD-trees ou Ball trees.",
      },
      {
        id: "ds9",
        text: "Que mesure le coefficient R² (R-squared) ?",
        options: [
          "L'erreur absolue moyenne",
          "La proportion de variance de la variable cible expliquée par le modèle (1 = parfait, 0 = pas mieux que la moyenne, <0 = pire que la moyenne)",
          "La corrélation entre deux variables",
          "La précision de classification",
        ],
        correctIndex: 1,
        explanation: "R² = 1 - SS_res/SS_tot. Un R² de 0.85 signifie que le modèle explique 85% de la variance. Attention : R² peut être élevé avec overfitting.",
      },
      {
        id: "ds10",
        text: "Comment gérer les valeurs manquantes dans un dataset ?",
        options: [
          "Toujours les supprimer",
          "Selon le contexte : supprimer si peu nombreuses et MCAR, imputer par médiane/mode/KNN/modèle si MAR, ou encoder la missingness comme feature si informative",
          "Les remplacer par 0",
          "Ignorer — les algorithmes ML gèrent automatiquement",
        ],
        correctIndex: 1,
        explanation: "MCAR/MAR/MNAR détermine la stratégie. L'imputation par médiane/mode est simple mais l'imputation multiple (MICE) est plus robuste. Parfois, 'est manquant' est lui-même informatif.",
      },
    ]),
  },
];

async function main() {
  console.log("Seeding quizzes...");
  for (const quiz of QUIZZES) {
    await prisma.quiz.upsert({
      where: { skill: quiz.skill },
      update: {
        title: quiz.title,
        description: quiz.description,
        difficulty: quiz.difficulty,
        timeLimit: quiz.timeLimit,
        questions: quiz.questions,
        isActive: true,
        updatedAt: new Date(),
      },
      create: quiz,
    });
    console.log(`  ✓ ${quiz.skill}`);
  }
  console.log("Done.");
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
